name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Pyralog ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build ${{ matrix.target }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_postfix: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_postfix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_postfix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/pyralog${{ matrix.binary_postfix }}
      
      - name: Package binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czf pyralog-${{ matrix.target }}.tar.gz pyralog${{ matrix.binary_postfix }}
          mv pyralog-${{ matrix.target }}.tar.gz ../../..
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./pyralog-${{ matrix.target }}.tar.gz
          asset_name: pyralog-${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip

  publish_crates:
    name: Publish to crates.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Publish pyralog-core
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p pyralog-core
      
      - name: Publish pyralog-protocol
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p pyralog-protocol
      
      - name: Publish pyralog-storage
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p pyralog-storage
      
      - name: Publish pyralog-consensus
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p pyralog-consensus
      
      - name: Publish pyralog-replication
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p pyralog-replication
      
      - name: Publish pyralog (main crate)
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

